### ISSUE TITLE
[VL] DATE_FORMAT(time_str, 'yyyyMMdd') BETWEEN  xx AND xx   query incorrect

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#3028]
### Backend

VL (Velox)

### Bug description

create table time_3 stored as parquet as
select 1 as id , '2023-01-01 08:00:00' as time_str union
select 2 as id , '2023-01-02 09:00:00' as time_str union
select 3 as id , '2023-01-03 10:00:00' as time_str;

select * from time_3 where DATE_FORMAT(time_str, 'yyyyMMdd') BETWEEN '20230101' AND '20230103';

### Spark version

None

**Comment by PHILO-HE** [comment]
It may be caused by a known issue: date is not correctly handled with local timezone. This known issue has been fixed by upstream Velox, but needs code rebase to get this issue addressed in Gluten.

**Comment by loukey-lj** [comment]
Through code analysis, it seems that velox/expression/CastExpr.cpp applyCastKernel does not implement string To Timestamp. After I try to add this implementation, there is still a problem. It seems that spark codegen will convert string to timestamp again; org.apache.spark.sql .catalyst.util.DateTimeUtils.stringToTimestamp(inputadapter_value_1, ((java.time.ZoneId) references[2] /* zoneId */));

Therefore, it is possible that a string is converted into a timestamp in velox and then converted into a string again into a timestamp, causing the data to not be found.

**Comment by loukey-lj** [comment]
We have solved it internally
